### ISSUE TITLE
html version of site is not working

### ISSUE THREAD

**Issue by godlikeswan** [txdv/cstrike-cvarlist#3]
![image](https://user-images.githubusercontent.com/14862534/142741034-4ee5fb70-d058-4aec-ab51-65eca4bbc22f.png)

**Comment by RauliTop** [comment]
@txdv check this issue.

New mirror can be get from here: https://nebulos.net/dl/cvar.html

**Comment by godlikeswan** [comment]
It displays all cvars now
However there are some troubles with css

`The resource from “https://nebulos.net/dl/style.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).`

https://nebulos.net/dl/style.css:
`The file you were looking for could not be found `
